using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Collections.Generic;

namespace UrbanIndicatorsSystem.CodeGeneration
{
    /// <summary>
    /// Code generator that creates controllers, DTOs, and services based on configuration
    /// </summary>
    public class CodeGenerator
    {
        private readonly string _configPath;
        private readonly string _outputPath;
        private readonly string _namespace;

        public CodeGenerator(string configPath, string outputPath, string namespaceName = "UrbanIndicatorsSystem")
        {
            _configPath = configPath;
            _outputPath = outputPath;
            _namespace = namespaceName;
        }

        public void Generate()
        {
            Console.WriteLine("=== Code Generation Started ===");
            
            if (!File.Exists(_configPath))
            {
                Console.WriteLine($"Configuration file not found: {_configPath}");
                return;
            }

            var config = JsonSerializer.Deserialize<EntityConfiguration>(
                File.ReadAllText(_configPath),
                new JsonSerializerOptions { PropertyNameCaseInsensitive = true }
            );

            if (config?.Entities == null)
            {
                Console.WriteLine("No entities found in configuration");
                return;
            }

            Directory.CreateDirectory(_outputPath);
            Directory.CreateDirectory(Path.Combine(_outputPath, "Controllers"));
            Directory.CreateDirectory(Path.Combine(_outputPath, "DTOs"));
            Directory.CreateDirectory(Path.Combine(_outputPath, "Services"));

            foreach (var entity in config.Entities)
            {
                Console.WriteLine($"Processing entity: {entity.Name}");
                
                if (entity.GenerateDto)
                    GenerateDTO(entity);
                    
                if (entity.GenerateController)
                    GenerateController(entity);
                    
                if (entity.GenerateService)
                    GenerateService(entity);
            }

            var generatedCount = config.Entities.Count(e => e.GenerateDto) +
                               config.Entities.Count(e => e.GenerateController) +
                               config.Entities.Count(e => e.GenerateService) * 2; // Service has 2 files
            Console.WriteLine($"=== Generated {generatedCount} files ===");
        }

        private void GenerateDTO(EntityConfig entity)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine($"// Generated on: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine();
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.ComponentModel.DataAnnotations;");
            sb.AppendLine();
            sb.AppendLine($"namespace {_namespace}.Generated.DTOs");
            sb.AppendLine("{");
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Data Transfer Object for {entity.Name}");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    public class {entity.Name}Dto");
            sb.AppendLine("    {");

            foreach (var prop in entity.Properties)
            {
                if (prop.IsRequired && prop.Type == "string")
                {
                    sb.AppendLine("        [Required]");
                }
                if (prop.MaxLength.HasValue && prop.Type == "string")
                {
                    sb.AppendLine($"        [MaxLength({prop.MaxLength.Value})]");
                }
                
                var propType = prop.Type;
                if (prop.Type == "DateTime" && !prop.IsRequired)
                {
                    propType = "DateTime?";
                }
                
                var requiredModifier = (prop.IsRequired && prop.Type == "string") ? "required " : "";
                sb.AppendLine($"        public {requiredModifier}{propType} {prop.Name} {{ get; set; }}");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            var fileName = Path.Combine(_outputPath, "DTOs", $"{entity.Name}Dto.cs");
            File.WriteAllText(fileName, sb.ToString());
            Console.WriteLine($"Generated DTO: {fileName}");
        }

        private void GenerateController(EntityConfig entity)
        {
            var dbSetName = entity.DbSetName ?? $"{entity.Name}s";
            
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine($"// Generated on: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine();
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
            sb.AppendLine("using Microsoft.EntityFrameworkCore;");
            sb.AppendLine($"using {_namespace}.Data;");
            sb.AppendLine($"using {_namespace}.Models;");
            sb.AppendLine($"using {_namespace}.Generated.DTOs;");
            sb.AppendLine();
            sb.AppendLine($"namespace {_namespace}.Generated.Controllers");
            sb.AppendLine("{");
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Auto-generated REST API Controller for {entity.Name}");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine("    [ApiController]");
            sb.AppendLine("    [Route(\"api/generated/[controller]\")]");
            sb.AppendLine($"    public class {entity.Name}Controller : ControllerBase");
            sb.AppendLine("    {");
            sb.AppendLine("        private readonly TrafficDbContext _context;");
            sb.AppendLine();
            sb.AppendLine($"        public {entity.Name}Controller(TrafficDbContext context)");
            sb.AppendLine("        {");
            sb.AppendLine("            _context = context;");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // GET all
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// Get all {entity.Name} entities");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        [HttpGet]");
            sb.AppendLine($"        public async Task<ActionResult<IEnumerable<{entity.Name}Dto>>> GetAll()");
            sb.AppendLine("        {");
            sb.AppendLine($"            var entities = await _context.{dbSetName}.ToListAsync();");
            sb.AppendLine($"            var dtos = entities.Select(e => MapToDto(e));");
            sb.AppendLine("            return Ok(dtos);");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // GET by id
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// Get a specific {entity.Name} by ID");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        [HttpGet(\"{id}\")]");
            sb.AppendLine($"        public async Task<ActionResult<{entity.Name}Dto>> GetById(int id)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var entity = await _context.{dbSetName}.FindAsync(id);");
            sb.AppendLine("            if (entity == null) return NotFound();");
            sb.AppendLine("            return Ok(MapToDto(entity));");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // POST
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// Create a new {entity.Name}");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        [HttpPost]");
            sb.AppendLine($"        public async Task<ActionResult<{entity.Name}Dto>> Create({entity.Name}Dto dto)");
            sb.AppendLine("        {");
            sb.AppendLine("            var entity = MapToEntity(dto);");
            sb.AppendLine($"            _context.{dbSetName}.Add(entity);");
            sb.AppendLine("            await _context.SaveChangesAsync();");
            sb.AppendLine("            return CreatedAtAction(nameof(GetById), new { id = entity.Id }, MapToDto(entity));");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // Mapping methods
            sb.AppendLine($"        private {entity.Name}Dto MapToDto({entity.Name} entity)");
            sb.AppendLine("        {");
            sb.AppendLine($"            return new {entity.Name}Dto");
            sb.AppendLine("            {");
            foreach (var prop in entity.Properties)
            {
                var comma = prop == entity.Properties[entity.Properties.Count - 1] ? "" : ",";
                sb.AppendLine($"                {prop.Name} = entity.{prop.Name}{comma}");
            }
            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            sb.AppendLine($"        private {entity.Name} MapToEntity({entity.Name}Dto dto)");
            sb.AppendLine("        {");
            sb.AppendLine($"            return new {entity.Name}");
            sb.AppendLine("            {");
            foreach (var prop in entity.Properties.Where(p => !p.IsPrimaryKey))
            {
                var comma = prop == entity.Properties.Where(p => !p.IsPrimaryKey).Last() ? "" : ",";
                sb.AppendLine($"                {prop.Name} = dto.{prop.Name}{comma}");
            }
            sb.AppendLine("            };");
            sb.AppendLine("        }");
            
            sb.AppendLine("    }");
            sb.AppendLine("}");

            var fileName = Path.Combine(_outputPath, "Controllers", $"{entity.Name}Controller.cs");
            File.WriteAllText(fileName, sb.ToString());
            Console.WriteLine($"Generated Controller: {fileName}");
        }

        private void GenerateService(EntityConfig entity)
        {
            var dbSetName = entity.DbSetName ?? $"{entity.Name}s";
            
            // Generate Interface
            var interfaceSb = new StringBuilder();
            interfaceSb.AppendLine("// <auto-generated />");
            interfaceSb.AppendLine($"// Generated on: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            interfaceSb.AppendLine();
            interfaceSb.AppendLine("#nullable enable");
            interfaceSb.AppendLine();
            interfaceSb.AppendLine("using System.Collections.Generic;");
            interfaceSb.AppendLine("using System.Threading.Tasks;");
            interfaceSb.AppendLine($"using {_namespace}.Models;");
            interfaceSb.AppendLine();
            interfaceSb.AppendLine($"namespace {_namespace}.Generated.Services");
            interfaceSb.AppendLine("{");
            interfaceSb.AppendLine($"    /// <summary>");
            interfaceSb.AppendLine($"    /// Service interface for {entity.Name}");
            interfaceSb.AppendLine($"    /// </summary>");
            interfaceSb.AppendLine($"    public interface I{entity.Name}Service");
            interfaceSb.AppendLine("    {");
            interfaceSb.AppendLine($"        Task<IEnumerable<{entity.Name}>> GetAllAsync();");
            interfaceSb.AppendLine($"        Task<{entity.Name}?> GetByIdAsync(int id);");
            interfaceSb.AppendLine($"        Task<{entity.Name}> CreateAsync({entity.Name} entity);");
            interfaceSb.AppendLine($"        Task<{entity.Name}?> UpdateAsync(int id, {entity.Name} entity);");
            interfaceSb.AppendLine($"        Task<bool> DeleteAsync(int id);");
            interfaceSb.AppendLine("    }");
            interfaceSb.AppendLine("}");

            var interfaceFileName = Path.Combine(_outputPath, "Services", $"I{entity.Name}Service.cs");
            File.WriteAllText(interfaceFileName, interfaceSb.ToString());
            Console.WriteLine($"Generated Service Interface: {interfaceFileName}");

            // Generate Implementation
            var serviceSb = new StringBuilder();
            serviceSb.AppendLine("// <auto-generated />");
            serviceSb.AppendLine($"// Generated on: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            serviceSb.AppendLine();
            serviceSb.AppendLine("#nullable enable");
            serviceSb.AppendLine();
            serviceSb.AppendLine("using System.Collections.Generic;");
            serviceSb.AppendLine("using System.Linq;");
            serviceSb.AppendLine("using System.Threading.Tasks;");
            serviceSb.AppendLine("using Microsoft.EntityFrameworkCore;");
            serviceSb.AppendLine($"using {_namespace}.Data;");
            serviceSb.AppendLine($"using {_namespace}.Models;");
            serviceSb.AppendLine();
            serviceSb.AppendLine($"namespace {_namespace}.Generated.Services");
            serviceSb.AppendLine("{");
            serviceSb.AppendLine($"    /// <summary>");
            serviceSb.AppendLine($"    /// Service implementation for {entity.Name}");
            serviceSb.AppendLine($"    /// </summary>");
            serviceSb.AppendLine($"    public class {entity.Name}Service : I{entity.Name}Service");
            serviceSb.AppendLine("    {");
            serviceSb.AppendLine("        private readonly TrafficDbContext _context;");
            serviceSb.AppendLine();
            serviceSb.AppendLine($"        public {entity.Name}Service(TrafficDbContext context)");
            serviceSb.AppendLine("        {");
            serviceSb.AppendLine("            _context = context;");
            serviceSb.AppendLine("        }");
            serviceSb.AppendLine();
            
            // GetAllAsync
            serviceSb.AppendLine($"        public async Task<IEnumerable<{entity.Name}>> GetAllAsync()");
            serviceSb.AppendLine("        {");
            serviceSb.AppendLine($"            return await _context.{dbSetName}.ToListAsync();");
            serviceSb.AppendLine("        }");
            serviceSb.AppendLine();
            
            // GetByIdAsync
            serviceSb.AppendLine($"        public async Task<{entity.Name}?> GetByIdAsync(int id)");
            serviceSb.AppendLine("        {");
            serviceSb.AppendLine($"            return await _context.{dbSetName}.FindAsync(id);");
            serviceSb.AppendLine("        }");
            serviceSb.AppendLine();
            
            // CreateAsync
            serviceSb.AppendLine($"        public async Task<{entity.Name}> CreateAsync({entity.Name} entity)");
            serviceSb.AppendLine("        {");
            serviceSb.AppendLine($"            _context.{dbSetName}.Add(entity);");
            serviceSb.AppendLine("            await _context.SaveChangesAsync();");
            serviceSb.AppendLine("            return entity;");
            serviceSb.AppendLine("        }");
            serviceSb.AppendLine();
            
            // UpdateAsync
            serviceSb.AppendLine($"        public async Task<{entity.Name}?> UpdateAsync(int id, {entity.Name} entity)");
            serviceSb.AppendLine("        {");
            serviceSb.AppendLine($"            var existing = await _context.{dbSetName}.FindAsync(id);");
            serviceSb.AppendLine("            if (existing == null) return null;");
            serviceSb.AppendLine();
            foreach (var prop in entity.Properties.Where(p => !p.IsPrimaryKey))
            {
                serviceSb.AppendLine($"            existing.{prop.Name} = entity.{prop.Name};");
            }
            serviceSb.AppendLine();
            serviceSb.AppendLine("            await _context.SaveChangesAsync();");
            serviceSb.AppendLine("            return existing;");
            serviceSb.AppendLine("        }");
            serviceSb.AppendLine();
            
            // DeleteAsync
            serviceSb.AppendLine($"        public async Task<bool> DeleteAsync(int id)");
            serviceSb.AppendLine("        {");
            serviceSb.AppendLine($"            var entity = await _context.{dbSetName}.FindAsync(id);");
            serviceSb.AppendLine("            if (entity == null) return false;");
            serviceSb.AppendLine();
            serviceSb.AppendLine($"            _context.{dbSetName}.Remove(entity);");
            serviceSb.AppendLine("            await _context.SaveChangesAsync();");
            serviceSb.AppendLine("            return true;");
            serviceSb.AppendLine("        }");
            
            serviceSb.AppendLine("    }");
            serviceSb.AppendLine("}");

            var serviceFileName = Path.Combine(_outputPath, "Services", $"{entity.Name}Service.cs");
            File.WriteAllText(serviceFileName, serviceSb.ToString());
            Console.WriteLine($"Generated Service Implementation: {serviceFileName}");
        }
    }

    public class EntityConfiguration
    {
        public string? Namespace { get; set; }
        public string? OutputDirectory { get; set; }
        public required List<EntityConfig> Entities { get; set; }
        public List<ApiVersionConfig>? ApiVersions { get; set; }
    }

    public class EntityConfig
    {
        public required string Name { get; set; }
        public string? DbSetName { get; set; }
        public required List<PropertyConfig> Properties { get; set; }
        public List<RelationshipConfig>? Relationships { get; set; }
        public bool GenerateController { get; set; } = true;
        public bool GenerateService { get; set; } = true;
        public bool GenerateDto { get; set; } = true;
    }

    public class PropertyConfig
    {
        public required string Name { get; set; }
        public required string Type { get; set; }
        public bool IsPrimaryKey { get; set; }
        public bool IsForeignKey { get; set; }
        public bool IsRequired { get; set; }
        public int? MaxLength { get; set; }
    }

    public class RelationshipConfig
    {
        public required string Name { get; set; }
        public required string Type { get; set; }
        public required string RelatedEntity { get; set; }
    }

    public class ApiVersionConfig
    {
        public required string Version { get; set; }
        public required List<string> Entities { get; set; }
        public required string Format { get; set; }
    }
}
