// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UrbanIndicatorsSystem.Data;

#nullable disable

namespace _.Migrations
{
    [DbContext(typeof(TrafficDbContext))]
    [Migration("20251025121608_AddTimestampToTraffic")]
    partial class AddTimestampToTraffic
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UrbanIndicatorsSystem.Models.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Shevchenkivskyi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pecherskyi"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Podilskyi"
                        });
                });

            modelBuilder.Entity("UrbanIndicatorsSystem.Models.TrafficData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("integer");

                    b.Property<string>("RoadName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TrafficLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TrafficData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AreaId = 1,
                            RoadName = "Shevchenkivskyi",
                            Timestamp = new DateTime(2025, 10, 25, 12, 16, 7, 846, DateTimeKind.Utc).AddTicks(6490),
                            TrafficLevel = "Low"
                        },
                        new
                        {
                            Id = 2,
                            AreaId = 2,
                            RoadName = "Pecherskyi",
                            Timestamp = new DateTime(2025, 10, 25, 12, 16, 7, 846, DateTimeKind.Utc).AddTicks(6590),
                            TrafficLevel = "Moderate"
                        },
                        new
                        {
                            Id = 3,
                            AreaId = 3,
                            RoadName = "Podilskyi",
                            Timestamp = new DateTime(2025, 10, 25, 12, 16, 7, 846, DateTimeKind.Utc).AddTicks(6590),
                            TrafficLevel = "High"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
